language: generic
services:
  - docker

before_install:
  - docker build -t fuqing04/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true fuqing04/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-533227296170"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "AKIAXYJWS2WVGR3HFIQN"
  secret_access_key: "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"
