language: generic
services:
  - docker

before_install:
  - docker build -t fuqing04/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true fuqing04/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-533227296170"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
